version: '3'
services:
  app:
    container_name: opl-front-prod
    image: opl-front-prod
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports: 
      - '0.0.0.0:3001:3000'
    volumes:
      - ./src:/app/src
    environment:
     - NODE_ENV='development'
     - CHOKIDAR_USEPOLLING=true
    networks:
      - production




