version: '3'

services:
  app:
    container_name: opl-front-dev
    image: opl-front-dev 
    stdin_open: true
    tty: true
    build: .
    ports: 
      - '0.0.0.0:3000:3000'
    volumes:
      - ./src:/app/src
    environment:
     - NODE_ENV='development'
    networks:
      - development



