version: '3'

services:
  app:
    container_name: opl-front-dev
    image: opl-front-dev 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports: 
      - '127.0.0.1:3000:3000'
    volumes:
      - ./src:/app/src
    environment:
     - NODE_ENV='development'



