version: '3'

services:
  nginx-dev: 
    container-name: nginx-dev-container
    image: nginx-dev
    build: 
      dockerfile: Dockerfile 
      context: . 
    ports:
    - "80:80"
    networks:
      - development
